sudo: required
dist: bionic
language: csharp
mono: none
dotnet:5.0
services: docker
before_install:
  - cd 18_RWANU_Docker/
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rwanu:$TRAVIS_JOB_ID $DOCKER_USERNAME/rwanu:$TRAVIS_JOB_ID
    docker tag rwanu-db:$TRAVIS_JOB_ID $DOCKER_USERNAME/rwanu-db:firstimage
    docker push $DOCKER_USERNAME/rwanu
    docker push $DOCKER_USERNAME/rwanu-db
  on:
    branch: master
notifications:
  email: false